# Generated by Django 5.0.4 on 2024-08-03 12:08

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='astronaut',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
