# Generated by Django 5.0.4 on 2024-08-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_astronaut_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='astronaut',
            managers=[
            ],
        ),
    ]
