# Generated by Django 5.0.4 on 2024-06-21 09:23

from django.db import migrations


def set_price(apps, schema_editor):
    MULTIPLY_PRICE = 120

    smartphone_model = apps.get_model("main_app", "Smartphone")

    for smartphone_record in smartphone_model.objects.all():
        smartphone_record.price = len(smartphone_record.brand) * MULTIPLY_PRICE
        smartphone_record.save()


def set_category(apps, schema_editor):
    smartphone_model = apps.get_model("main_app", "Smartphone")

    for smartphone_record in smartphone_model.objects.all():
        if smartphone_record.price >= 750:
            smartphone_record.category = "Expensive"
        else:
            smartphone_record.category = "Cheap"
        smartphone_record.save()


def set_category_and_price(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


def reverse_code(apps, schema_editor):
    smartphone_model = apps.get_model("main_app", "Smartphone")

    for smartphone_record in smartphone_model.objects.all():
        smartphone_record.price = 0
        smartphone_record.category = "No category"

        smartphone_record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_category_and_price, reverse_code=reverse_code),
    ]
